### create
POST http://localhost:8080/api/tree/node
Content-Type: application/json

{
  "name": "my-tree-node-name",
  "content": "my-tree-node-content"
}

### delete
DELETE http://localhost:8080/api/tree/node/2
Content-Type: application/json

### getRootNode
GET http://localhost:8080/api/tree
Content-Type: application/json

### listTree
GET http://localhost:8080/api/tree/node/list
Content-Type: application/json

### move
PUT http://localhost:8080/api/tree/move/3/2
Content-Type: application/json

### load
GET http://localhost:8080/api/tree/content/2
Content-Type: application/json

### search
GET http://localhost:8080/api/tree/search
Content-Type: application/json
